In [1]:
import numpy as np 
import csv 
import pandas as pd
import xlrd
from matplotlib import pyplot as plt

#import jour de référence
df = pd.read_csv("7janvier.csv")
df=df.dropna()
jourCherche = df.Consommation
#print("Contents :", jourCherche)

#import RTE
df = pd.read_csv('RTE.csv')
df=df.dropna()
data2020 = df.Consommation
#print("Contents :", data2020)

#formatage de l'objet RTE panda en tableau compréhensible
array_jour_ref = []
for i in data2020:
    array_jour_ref.append(i)

#print(len(array_jour))

array_jour_cherche = []
#formatage du jour du 7 janvier pour avoir un tableau identique
for i in jourCherche:
    array_jour_cherche.append(i)


#etape 1 : separation des jours du RTE
#il y a 366 jours en 2020 donc on divise par 366 
array_splited = np.array_split(array_jour_ref, 366)
print(len(array_jour_cherche))

print(len(array_splited[0]))

#etape 2 : corrélation entre chaque jour 
def create_correlation_matrix(x, y):
    return np.corrcoef(x, y)
    
correl_array = []  
x = np.array(array_jour_cherche)
y = np.array(array_splited)
print(create_correlation_matrix(x, y))
    
    
    
    
    
    
print(correl_array)

def mainProgram():
    pass



48
48
[[1.         0.56207381 0.93797595 ... 0.96968362 0.96107644 0.97718042]
 [0.56207381 1.         0.31056622 ... 0.44028215 0.38451081 0.4532694 ]
 [0.93797595 0.31056622 1.         ... 0.98472008 0.9866689  0.97935391]
 ...
 [0.96968362 0.44028215 0.98472008 ... 1.         0.99554725 0.98414087]
 [0.96107644 0.38451081 0.9866689  ... 0.99554725 1.         0.98195956]
 [0.97718042 0.4532694  0.97935391 ... 0.98414087 0.98195956 1.        ]]
[]
